### ISSUE TITLE
Assign me

### ISSUE THREAD

**Issue by Kesav890** [IumoInfinium/hacktober21-C-Programming#7]
I would like to add Insertion sort.Assign me

**Comment by jash458** [comment]
I will add bubble sort
so please assign me.

**Comment by Kesav890** [comment]
Sorry bro its not my issue I just participated in it

**Comment by jash458** [comment]
But you just need to do 1 more step , that it's just label my PR with
Hacktoberfest, Hacktoberfest 2021. Please bro else it will not count.
